[build]
  functions = "functions"
  command = "yarn run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://jamstack-poc.netlify.app/api/*"
  to = "https://jamstack-poc.netlify.app/.netlify/functions/:splat"
  status = 200
